// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: transaction_service.proto

package transaction

import (
	_go "github.com/nyakovchuk/contracts/pagination/go"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DepositRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        uint64                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositRequest) Reset() {
	*x = DepositRequest{}
	mi := &file_transaction_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositRequest) ProtoMessage() {}

func (x *DepositRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositRequest.ProtoReflect.Descriptor instead.
func (*DepositRequest) Descriptor() ([]byte, []int) {
	return file_transaction_service_proto_rawDescGZIP(), []int{0}
}

func (x *DepositRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DepositRequest) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type WithdrawRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        uint64                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawRequest) Reset() {
	*x = WithdrawRequest{}
	mi := &file_transaction_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawRequest) ProtoMessage() {}

func (x *WithdrawRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawRequest.ProtoReflect.Descriptor instead.
func (*WithdrawRequest) Descriptor() ([]byte, []int) {
	return file_transaction_service_proto_rawDescGZIP(), []int{1}
}

func (x *WithdrawRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *WithdrawRequest) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type TransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        uint64                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Recipient     uint64                 `protobuf:"varint,3,opt,name=recipient,proto3" json:"recipient,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferRequest) Reset() {
	*x = TransferRequest{}
	mi := &file_transaction_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferRequest) ProtoMessage() {}

func (x *TransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferRequest.ProtoReflect.Descriptor instead.
func (*TransferRequest) Descriptor() ([]byte, []int) {
	return file_transaction_service_proto_rawDescGZIP(), []int{2}
}

func (x *TransferRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TransferRequest) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransferRequest) GetRecipient() uint64 {
	if x != nil {
		return x.Recipient
	}
	return 0
}

type GetTransactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        *uint64                `protobuf:"varint,1,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	Type          *string                `protobuf:"bytes,2,opt,name=type,proto3,oneof" json:"type,omitempty"`
	Status        *string                `protobuf:"bytes,3,opt,name=status,proto3,oneof" json:"status,omitempty"`
	DateFrom      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=date_from,json=dateFrom,proto3,oneof" json:"date_from,omitempty"`
	DateTo        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=date_to,json=dateTo,proto3,oneof" json:"date_to,omitempty"`
	Pagination    *_go.Pagination        `protobuf:"bytes,6,opt,name=pagination,proto3,oneof" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsRequest) Reset() {
	*x = GetTransactionsRequest{}
	mi := &file_transaction_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsRequest) ProtoMessage() {}

func (x *GetTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_transaction_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetTransactionsRequest) GetUserId() uint64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *GetTransactionsRequest) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *GetTransactionsRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *GetTransactionsRequest) GetDateFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.DateFrom
	}
	return nil
}

func (x *GetTransactionsRequest) GetDateTo() *timestamppb.Timestamp {
	if x != nil {
		return x.DateTo
	}
	return nil
}

func (x *GetTransactionsRequest) GetPagination() *_go.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*TransactionDetails  `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsResponse) Reset() {
	*x = GetTransactionsResponse{}
	mi := &file_transaction_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsResponse) ProtoMessage() {}

func (x *GetTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_transaction_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetTransactionsResponse) GetTransactions() []*TransactionDetails {
	if x != nil {
		return x.Transactions
	}
	return nil
}

var File_transaction_service_proto protoreflect.FileDescriptor

const file_transaction_service_proto_rawDesc = "" +
	"\n" +
	"\x19transaction_service.proto\x12\vtransaction\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bpagination/pagination.proto\x1a\x17transaction_model.proto\"A\n" +
	"\x0eDepositRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x04R\x06amount\"B\n" +
	"\x0fWithdrawRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x04R\x06amount\"`\n" +
	"\x0fTransferRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x04R\x06amount\x12\x1c\n" +
	"\trecipient\x18\x03 \x01(\x04R\trecipient\"\xea\x02\n" +
	"\x16GetTransactionsRequest\x12\x1c\n" +
	"\auser_id\x18\x01 \x01(\x04H\x00R\x06userId\x88\x01\x01\x12\x17\n" +
	"\x04type\x18\x02 \x01(\tH\x01R\x04type\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x03 \x01(\tH\x02R\x06status\x88\x01\x01\x12<\n" +
	"\tdate_from\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x03R\bdateFrom\x88\x01\x01\x128\n" +
	"\adate_to\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x04R\x06dateTo\x88\x01\x01\x12;\n" +
	"\n" +
	"pagination\x18\x06 \x01(\v2\x16.pagination.PaginationH\x05R\n" +
	"pagination\x88\x01\x01B\n" +
	"\n" +
	"\b_user_idB\a\n" +
	"\x05_typeB\t\n" +
	"\a_statusB\f\n" +
	"\n" +
	"_date_fromB\n" +
	"\n" +
	"\b_date_toB\r\n" +
	"\v_pagination\"^\n" +
	"\x17GetTransactionsResponse\x12C\n" +
	"\ftransactions\x18\x01 \x03(\v2\x1f.transaction.TransactionDetailsR\ftransactions2\xb6\x02\n" +
	"\x12TransactionService\x12>\n" +
	"\aDeposit\x12\x1b.transaction.DepositRequest\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\bWithdraw\x12\x1c.transaction.WithdrawRequest\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\bTransfer\x12\x1c.transaction.TransferRequest\x1a\x16.google.protobuf.Empty\x12\\\n" +
	"\x0fGetTransactions\x12#.transaction.GetTransactionsRequest\x1a$.transaction.GetTransactionsResponseB<Z:github.com/nyakovchuk/contracts/transaction/go;transactionb\x06proto3"

var (
	file_transaction_service_proto_rawDescOnce sync.Once
	file_transaction_service_proto_rawDescData []byte
)

func file_transaction_service_proto_rawDescGZIP() []byte {
	file_transaction_service_proto_rawDescOnce.Do(func() {
		file_transaction_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transaction_service_proto_rawDesc), len(file_transaction_service_proto_rawDesc)))
	})
	return file_transaction_service_proto_rawDescData
}

var file_transaction_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_transaction_service_proto_goTypes = []any{
	(*DepositRequest)(nil),          // 0: transaction.DepositRequest
	(*WithdrawRequest)(nil),         // 1: transaction.WithdrawRequest
	(*TransferRequest)(nil),         // 2: transaction.TransferRequest
	(*GetTransactionsRequest)(nil),  // 3: transaction.GetTransactionsRequest
	(*GetTransactionsResponse)(nil), // 4: transaction.GetTransactionsResponse
	(*timestamppb.Timestamp)(nil),   // 5: google.protobuf.Timestamp
	(*_go.Pagination)(nil),          // 6: pagination.Pagination
	(*TransactionDetails)(nil),      // 7: transaction.TransactionDetails
	(*emptypb.Empty)(nil),           // 8: google.protobuf.Empty
}
var file_transaction_service_proto_depIdxs = []int32{
	5, // 0: transaction.GetTransactionsRequest.date_from:type_name -> google.protobuf.Timestamp
	5, // 1: transaction.GetTransactionsRequest.date_to:type_name -> google.protobuf.Timestamp
	6, // 2: transaction.GetTransactionsRequest.pagination:type_name -> pagination.Pagination
	7, // 3: transaction.GetTransactionsResponse.transactions:type_name -> transaction.TransactionDetails
	0, // 4: transaction.TransactionService.Deposit:input_type -> transaction.DepositRequest
	1, // 5: transaction.TransactionService.Withdraw:input_type -> transaction.WithdrawRequest
	2, // 6: transaction.TransactionService.Transfer:input_type -> transaction.TransferRequest
	3, // 7: transaction.TransactionService.GetTransactions:input_type -> transaction.GetTransactionsRequest
	8, // 8: transaction.TransactionService.Deposit:output_type -> google.protobuf.Empty
	8, // 9: transaction.TransactionService.Withdraw:output_type -> google.protobuf.Empty
	8, // 10: transaction.TransactionService.Transfer:output_type -> google.protobuf.Empty
	4, // 11: transaction.TransactionService.GetTransactions:output_type -> transaction.GetTransactionsResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_transaction_service_proto_init() }
func file_transaction_service_proto_init() {
	if File_transaction_service_proto != nil {
		return
	}
	file_transaction_model_proto_init()
	file_transaction_service_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transaction_service_proto_rawDesc), len(file_transaction_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transaction_service_proto_goTypes,
		DependencyIndexes: file_transaction_service_proto_depIdxs,
		MessageInfos:      file_transaction_service_proto_msgTypes,
	}.Build()
	File_transaction_service_proto = out.File
	file_transaction_service_proto_goTypes = nil
	file_transaction_service_proto_depIdxs = nil
}
